name: 1804.$(Date:yyyyMMdd)$(Rev:.r)
jobs:
- job: Build Vagrant Box - ubuntu-desktop - hyperv
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 10
  strategy:
    parallel: 1
  pool:
    name: default

  variables:
    - group: ubuntu-desktop-bootstrap

  steps:
    - bash: setup/install-awscli.sh
      displayName: Ensure AWS CLI is installed.
      env:
        AWS_ACCESS_KEY: $(s3_access_key)
        AWS_SECRET_ACCESS_KEY: $(s3_secret_key)

    - powershell: ./build.ps1 -publish
      timeoutInMinutes: 0
      displayName: 'Run packer hyper-v build'
      env:
        AWS_ACCESS_KEY: $(s3_access_key)
        AWS_SECRET_ACCESS_KEY: $(s3_secret_key)
    
    - bash: scripts/upload.sh
      displayNmae: Upload to Wasabi S3 storage
      timeoutInMinutes: 0
      env:
        VAGRANT_BOX_NAME: ubuntu-desktop
        VAGRANT_PROVIDER_TYPE: hyperv

    - bash: scripts/publish.sh
      displayName: Publish version to Vagrant Cloud
      env:
        VAGRANT_CLOUD_TOKEN: $(vagrant_token)
        VAGRANT_CLOUD_USERNAME: estenrye
        VAGRANT_BOX_NAME: ubuntu-desktop
        VAGRANT_PROVIDER_TYPE: hyperv

    - bash: scripts/release.sh
      displayName: Release published version on Vagrant Cloud.
      env:
        VAGRANT_CLOUD_TOKEN: $(vagrant_token)
        VAGRANT_CLOUD_USERNAME: estenrye
        VAGRANT_BOX_NAME: ubuntu-desktop
