jobs:
- job: string
  timeoutInMinutes: 0
  cancelTimeoutInMinutes: 10
  strategy:
    parallel: 1
  pool:
    name: default

  steps:
    - script: echo Hello world
# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# timeoutInMinutes: 120
  # trigger:
  #   - master

# pool: default

  variables:
    - group: ubuntu-desktop-bootstrap

# steps:
# - bash: setup/install-awscli.sh
#   env:
#     AWS_ACCESS_KEY: $(s3_access_key)
#     AWS_SECRET_ACCESS_KEY: $(s3_secret_key)

# - powershell: ./build.ps1 -publish
#   timeoutInMinutes: 0
#   displayName: 'Run packer hyper-v build'
#   env:
#     AWS_ACCESS_KEY: $(s3_access_key)
#     AWS_SECRET_ACCESS_KEY: $(s3_secret_key)
#     VAGRANT_CLOUD_TOKEN: $(vagrant_token)
