---
- name: Install Oracle VirtualBox Repository Key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
  become: yes

- name: Add Oracle VirtualBox Repository
  apt_repository:
    repo: "{{ virtualbox.repository }}"
    state: present
  become: yes

- name: Install Oracle VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox.version }}"
    state: latest
    update_cache: yes
  become: yes