---
- name: download dotnet registry package.
  get_url:
    dest: /opt/ansible/packages/packages-microsoft-prod.deb
    url: https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    sha256sum: "{{dotnet_sha256sum}}"
  register: dotnet_download
  become: yes

- name: Install dotnet registry package.
  apt:
    deb: /opt/ansible/packages/packages-microsoft-prod.deb
    state: present
  when: dotnet_download.changed
  become: yes

- name: Install dotnet core.
  apt:
    name: "dotnet-sdk-{{ dotnet_version }}"
    state: latest
    update_cache: yes
  become: yes

